apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
- namespace.yaml
- ../../base
- argo-workflows-sso.yaml
- ingress-argo-workflows.yaml
patchesStrategicMerge:
- argo-server-auth-by-argocd-patch.yaml
- workflow-controller-configmap-patch.yaml
