apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          image: k8sgcriosigstorage/nfs-subdir-external-provisioner:v4.0.2
          env:
            - name: NFS_SERVER
              value: nfs-server.nfs.svc.cluster.local
            - name: NFS_PATH
              value: /ifs/kubernetes
      volumes:
        - name: nfs-client-root
          nfs:
            server: nfs-server.nfs.svc.cluster.local
            path: /ifs/kubernetes
