apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- ../../base
- argo-workflows-sso.yaml
- ingress-argocd.yaml
patchesStrategicMerge:
- argocd-cm-dex-connector-patch.yaml
- argocd-dex-server-patch.yaml
- argocd-dex-server-support-auth-argo-workflows-patch.yaml
