apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex
resources:
- ../../base
- dex-secret.yaml
- dex.example.com.tls.yaml
- ingress-dex.yaml
patchesStrategicMerge:
- dex-cm-patch.yaml
- dex-deployment-patch.yaml
